name: ✨ Feature Suggestion
description: Suggest a new feature or improvement for Open Notebook
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Your ideas help make Open Notebook better for everyone.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added or improved?
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: why-helpful
    attributes:
      label: Why would this be helpful?
      description: Explain how this feature would benefit you and other users
      placeholder: "This would help because..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution (Optional)
      description: If you have ideas on how to implement this feature, please share them
      placeholder: "This could be implemented by..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples that might be helpful
      placeholder: "For example, other tools do this by..."
    validations:
      required: false

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you like to work on implementing this feature?
      options:
        - label: I am a developer and would like to work on implementing this feature (pending maintainer approval)
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Next Steps:**
        1. A maintainer will review your feature request
        2. If approved and you checked the box above, the issue will be assigned to you
        3. Please wait for assignment before starting development
        4. See our [Contributing Guide](https://github.com/lfnovo/open-notebook/blob/main/CONTRIBUTING.md) for more details

